export const fakeLiveScan =  [
    {
      imageUrl: "https://storage.googleapis.com/www.clintonrivertraffic.com/images/vessels/mmsi368039740.jpg",
      liveCallSign: null,
      liveCourse: 250.9,
      liveDirection: "upriver",
      liveDraft: null,
      liveEvent: "camanche",
      liveEvents: [
        {camanche: 1645582322}
      ],
      liveInitLat: 41.786653333333334,
      liveInitLon: -90.24742,
      liveInitTS: 1645582281,
      liveIsLocal: false,
      liveLastLat: 41.786665,
      liveLastLon: -90.24739333333333,
      liveLastTS: 1645582322,
      liveLength: null,
      liveLocation: "In Camanche Harbor",
      liveMarkerAlphaTS: null,
      liveMarkerAlphaWasReached: false,
      liveMarkerBravoTS: null,
      liveMarkerBravoWasReached: false,
      liveMarkerCharlieTS: null,
      liveMarkerCharlieWasReached: false,
      liveMarkerDeltaTS: null,
      liveMarkerDeltaWasReached: false,
      liveName: "Artco Innovation",
      livePassageWasSaved: false,
      liveSpeed: 0,
      liveVesselID: 368039740,
      liveWidth: null,
      type: "Towing" 
    },
    
    {
      imageUrl: "https://storage.googleapis.com/www.clintonrivertraffic.com/images/vessels/no-image-placard.jpg",
      liveCallSign: null,
      liveCourse: 360,
      liveDirection: "undetermined",
      liveDraft: null,
      liveInitLat: 42.062215,
      liveInitLon: -90.17094166666666,
      liveInitTS: 1645582333,
      liveIsLocal: false,
      liveLastTS: 1645582333,
      liveLength: null,
      liveLocation: "Out back yonder",
      liveName: "Lisa Nicole",
      liveSpeed: 0,
      liveVesselID: 367520810,
      liveWidth: null,
      type: "Other Type" 
    },
       
    {
      imageUrl: "https://storage.googleapis.com/www.clintonrivertraffic.com/images/vessels/mmsi366970820.jpg",
      liveCallSign: null,
      liveCourse: 32.2,
      liveDirection: "upriver",
      liveDraft: null,
      liveEvent: "m512ua",
      liveEvents: [
        {m512ua: 1645582285}
      ],
      liveInitLat: 41.78609333333333,
      liveInitLon: -90.24452,
      liveInitTS: 1645582264,
      liveIsLocal: true,
      liveLastLat: 41.78613166666667,
      liveLastLon: -90.24451,
      liveLastTS: 1645582284,
      liveLength: null,
      liveLocation: "At M-512 by Camanche marina 6 miles below Clinton drawbridge",
      liveMarkerAlphaTS: null,
      liveMarkerAlphaWasReached: false,
      liveMarkerBravoTS: null,
      liveMarkerBravoWasReached: false,
      liveMarkerCharlieTS: null,
      liveMarkerCharlieWasReached: false,
      liveMarkerDeltaTS: null,
      liveMarkerDeltaWasReached: false,
      liveName: "Terrebonne",
      livePassageWasSaved: false,
      liveSpeed: 0,
      liveVesselID: 366970820,
      liveWidth: null,
      type: "Towing" 
    },
    
    {
    imageUrl: "https://storage.googleapis.com/www.clintonrivertraffic.com/images/vessels/mmsi366986460.jpg",
    liveCallSign: null,
    liveCourse: 331.5,
    liveDirection: "downriver",
    liveDraft: null,
    liveEvent: "camanche",
    liveEvents:[
      {camanche: 1645582293}
    ],
    liveInitLat: 41.79203666666667,
    liveInitLon: -90.24426666666666,
    liveInitTS: 1645582271,
    liveIsLocal: false,
    liveLastLat: 41.79204333333333,
    liveLastLon: -90.24426333333334,
    liveLastTS: 1645582293,
    liveLength: null,
    liveLocation: "In Camanche Harbor",
    liveMarkerAlphaTS: null,
    liveMarkerAlphaWasReached: false,
    liveMarkerBravoTS: null,
    liveMarkerBravoWasReached: false,
    liveMarkerCharlieTS: null,
    liveMarkerCharlieWasReached: false,
    liveMarkerDeltaTS: null,
    liveMarkerDeltaWasReached: false,
    liveName: "Lil Charley",
    livePassageWasSaved: false,
    liveSpeed: 0,
    liveVesselID: 366986460,
    liveWidth: null,
    type: "Towing"
    },
    
    
    {
      imageUrl: "https://storage.googleapis.com/www.clintonrivertraffic.com/images/vessels/mmsi368039740.jpg",
      liveCallSign: null,
      liveCourse: 250.9,
      liveDirection: "upriver",
      liveDraft: null,
      liveEvent: "camanche",
      liveEvents: [
        {camanche: 1645582322}
      ],
      liveInitLat: 41.786653333333334,
      liveInitLon: -90.24742,
      liveInitTS: 1645582281,
      liveIsLocal: false,
      liveLastLat: 41.786665,
      liveLastLon: -90.24739333333333,
      liveLastTS: 1645582322,
      liveLength: null,
      liveLocation: "In Camanche Harbor",
      liveMarkerAlphaTS: null,
      liveMarkerAlphaWasReached: false,
      liveMarkerBravoTS: null,
      liveMarkerBravoWasReached: false,
      liveMarkerCharlieTS: null,
      liveMarkerCharlieWasReached: false,
      liveMarkerDeltaTS: null,
      liveMarkerDeltaWasReached: false,
      liveName: "Fake Boat 7",
      livePassageWasSaved: false,
      liveSpeed: 0,
      liveVesselID: 368039740,
      liveWidth: null,
      type: "Towing" 
    }, 
    
    {
      imageUrl: "https://storage.googleapis.com/www.clintonrivertraffic.com/images/vessels/mmsi368039740.jpg",
      liveCallSign: null,
      liveCourse: 250.9,
      liveDirection: "upriver",
      liveDraft: null,
      liveEvent: "camanche",
      liveEvents: [
        {camanche: 1645582322}
      ],
      liveInitLat: 41.786653333333334,
      liveInitLon: -90.24742,
      liveInitTS: 1645582281,
      liveIsLocal: false,
      liveLastLat: 41.786665,
      liveLastLon: -90.24739333333333,
      liveLastTS: 1645582322,
      liveLength: null,
      liveLocation: "In Camanche Harbor",
      liveMarkerAlphaTS: null,
      liveMarkerAlphaWasReached: false,
      liveMarkerBravoTS: null,
      liveMarkerBravoWasReached: false,
      liveMarkerCharlieTS: null,
      liveMarkerCharlieWasReached: false,
      liveMarkerDeltaTS: null,
      liveMarkerDeltaWasReached: false,
      liveName: "Fat Freddy",
      livePassageWasSaved: false,
      liveSpeed: 0,
      liveVesselID: 368039740,
      liveWidth: null,
      type: "Towing" 
    },
    
    {
      imageUrl: "https://storage.googleapis.com/www.clintonrivertraffic.com/images/vessels/no-image-placard.jpg",
      liveCallSign: null,
      liveCourse: 360,
      liveDirection: "undetermined",
      liveDraft: null,
      liveInitLat: 42.062215,
      liveInitLon: -90.17094166666666,
      liveInitTS: 1645582333,
      liveIsLocal: false,
      liveLastTS: 1645582333,
      liveLength: null,
      liveLocation: "The moon",
      liveName: "Plunderer",
      liveSpeed: 0,
      liveVesselID: 367520810,
      liveWidth: null,
      type: "Other Type" 
    },
       
    {
      imageUrl: "https://storage.googleapis.com/www.clintonrivertraffic.com/images/vessels/mmsi366970820.jpg",
      liveCallSign: null,
      liveCourse: 32.2,
      liveDirection: "upriver",
      liveDraft: null,
      liveEvent: "m512ua",
      liveEvents: [
        {m512ua: 1645582285}
      ],
      liveInitLat: 41.78609333333333,
      liveInitLon: -90.24452,
      liveInitTS: 1645582264,
      liveIsLocal: true,
      liveLastLat: 41.78613166666667,
      liveLastLon: -90.24451,
      liveLastTS: 1645582284,
      liveLength: null,
      liveLocation: "At M-512 by Camanche marina 6 miles below Clinton drawbridge",
      liveMarkerAlphaTS: null,
      liveMarkerAlphaWasReached: false,
      liveMarkerBravoTS: null,
      liveMarkerBravoWasReached: false,
      liveMarkerCharlieTS: null,
      liveMarkerCharlieWasReached: false,
      liveMarkerDeltaTS: null,
      liveMarkerDeltaWasReached: false,
      liveName: "Take Me To Dinner",
      livePassageWasSaved: false,
      liveSpeed: 0,
      liveVesselID: 366970820,
      liveWidth: null,
      type: "Towing" 
    },
    
    {
      imageUrl: "https://storage.googleapis.com/www.clintonrivertraffic.com/images/vessels/mmsi368039740.jpg",
      liveCallSign: null,
      liveCourse: 250.9,
      liveDirection: "upriver",
      liveDraft: null,
      liveEvent: "camanche",
      liveEvents: [
        {camanche: 1645582322}
      ],
      liveInitLat: 41.786653333333334,
      liveInitLon: -90.24742,
      liveInitTS: 1645582281,
      liveIsLocal: false,
      liveLastLat: 41.786665,
      liveLastLon: -90.24739333333333,
      liveLastTS: 1645582322,
      liveLength: null,
      liveLocation: "In Camanche Harbor",
      liveMarkerAlphaTS: null,
      liveMarkerAlphaWasReached: false,
      liveMarkerBravoTS: null,
      liveMarkerBravoWasReached: false,
      liveMarkerCharlieTS: null,
      liveMarkerCharlieWasReached: false,
      liveMarkerDeltaTS: null,
      liveMarkerDeltaWasReached: false,
      liveName: "Bubbalicious",
      livePassageWasSaved: false,
      liveSpeed: 0,
      liveVesselID: 368039740,
      liveWidth: null,
      type: "Towing" 
    },
    
    
    {
      imageUrl: "https://storage.googleapis.com/www.clintonrivertraffic.com/images/vessels/mmsi368039740.jpg",
      liveCallSign: null,
      liveCourse: 250.9,
      liveDirection: "upriver",
      liveDraft: null,
      liveEvent: "camanche",
      liveEvents: [
        {camanche: 1645582322}
      ],
      liveInitLat: 41.786653333333334,
      liveInitLon: -90.24742,
      liveInitTS: 1645582281,
      liveIsLocal: false,
      liveLastLat: 41.786665,
      liveLastLon: -90.24739333333333,
      liveLastTS: 1645582322,
      liveLength: null,
      liveLocation: "In Camanche Harbor",
      liveMarkerAlphaTS: null,
      liveMarkerAlphaWasReached: false,
      liveMarkerBravoTS: null,
      liveMarkerBravoWasReached: false,
      liveMarkerCharlieTS: null,
      liveMarkerCharlieWasReached: false,
      liveMarkerDeltaTS: null,
      liveMarkerDeltaWasReached: false,
      liveName: "Croakalopis",
      livePassageWasSaved: false,
      liveSpeed: 0,
      liveVesselID: 368039740,
      liveWidth: null,
      type: "Towing" 
    },

        {
      imageUrl: "https://storage.googleapis.com/www.clintonrivertraffic.com/images/vessels/no-image-placard.jpg",
      liveCallSign: null,
      liveCourse: 360,
      liveDirection: "undetermined",
      liveDraft: null,
      liveInitLat: 42.062215,
      liveInitLon: -90.17094166666666,
      liveInitTS: 1645582333,
      liveIsLocal: false,
      liveLastTS: 1645582333,
      liveLength: null,
      liveLocation: "At M-512 by Camanche marina 6 miles below Clinton drawbridge",
      liveName: "Trail Blazer",
      liveSpeed: 0,
      liveVesselID: 367520810,
      liveWidth: null,
      type: "Other Type" 
    },
       
    {
      imageUrl: "https://storage.googleapis.com/www.clintonrivertraffic.com/images/vessels/mmsi366970820.jpg",
      liveCallSign: null,
      liveCourse: 32.2,
      liveDirection: "upriver",
      liveDraft: null,
      liveEvent: "m512ua",
      liveEvents: [
        {m512ua: 1645582285}
      ],
      liveInitLat: 41.78609333333333,
      liveInitLon: -90.24452,
      liveInitTS: 1645582264,
      liveIsLocal: true,
      liveLastLat: 41.78613166666667,
      liveLastLon: -90.24451,
      liveLastTS: 1645582284,
      liveLength: null,
      liveLocation: "At M-512 by Camanche marina 6 miles below Clinton drawbridge",
      liveMarkerAlphaTS: null,
      liveMarkerAlphaWasReached: false,
      liveMarkerBravoTS: null,
      liveMarkerBravoWasReached: false,
      liveMarkerCharlieTS: null,
      liveMarkerCharlieWasReached: false,
      liveMarkerDeltaTS: null,
      liveMarkerDeltaWasReached: false,
      liveName: "Roadster",
      livePassageWasSaved: false,
      liveSpeed: 0,
      liveVesselID: 366970820,
      liveWidth: null,
      type: "Towing" 
    }
]